### ISSUE TITLE
Make better use of Github tools for managing projects

### ISSUE THREAD

**Issue by boonwj** [boonwj/testtesttest#14]
## Description

Make better use of Github's toolset to manage a project.

Explore the different Github tools such as the improved task lists, milestones and issue templates.

## Tasks

- [x] #15
- [x] #17
- [x] #19
- [x] Get comments from @oyfml
- [x] Decide on final approach
- [ ] Bring over to dsaidgovsg/tcs-core#158

## Estimates

Effort Size: M
Estimated Time: 3 days

## Additional Information / References

Github Task List: https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

**Comment by boonwj** [comment]
Tasks can be converted to issues
![image](https://user-images.githubusercontent.com/3538312/124087922-0daed800-da85-11eb-844d-07b75c774612.png)

**Comment by boonwj** [comment]
For big issues or an issue that consolidates all the items in a backlog, perhaps we can just pin it.

![image](https://user-images.githubusercontent.com/3538312/124158432-7e2d1780-dacc-11eb-855e-643a45b01c09.png)

**Comment by boonwj** [comment]
Alternatively, if we look at the project boards. We can have 1 column to represent a backlog item, and the issues within are the tasks required to complete the backlog.

**Comment by boonwj** [comment]
# Using Milestones

Milestones are created from the issues page, in a somewhat obscure location.

![image](https://user-images.githubusercontent.com/3538312/124165816-ccdeaf80-dad4-11eb-8e3d-eeebc59de307.png)

Once created, issues and PRs can be assigned to a milestone. Progress can be seen either within the milestones page or on the sidebar of issues assigned to a milestone.

![image](https://user-images.githubusercontent.com/3538312/124165876-df58e900-dad4-11eb-9472-3083d94c1e64.png)

Issues associated with a milestone can be easily filtered in the issue page

![image](https://user-images.githubusercontent.com/3538312/124166583-9ce3dc00-dad5-11eb-93a3-de065ec9f857.png)

---

## Pros
* Easy to assign issues/prs to milestones as and when it is created
* Nice progress bar to see progress
* Easily see all issues and prs by filtering in the issues page

## Cons
* Can't be tagged to the project board
